import React, { useState } from 'react';
import { Check, Copy, Mail, MessageSquare, Send, X } from 'lucide-react';
import { parseCurrencyAmount } from '../utils/parsers';
import { scoreLabel } from '../utils/format';

export default function ReportModal({ profile, results, onClose }) {
  const [mode,      setMode]      = useState("whatsapp");
  const [copied,    setCopied]    = useState(false);
  const [phone,     setPhone]     = useState("");
  const [emailAddr, setEmailAddr] = useState("");

  const wa = profile && results ? `🎓 *VisaLens Student Report*
━━━━━━━━━━━━━━━━━━
👤 *Student:* ${profile.fullName||"N/A"}
🌍 *Nationality:* ${profile.nationality||"N/A"}
📅 *DOB:* ${profile.dob||"N/A"}
🛂 *Passport:* ${profile.passportNumber||"N/A"} (Exp: ${profile.passportExpiry||"N/A"})${(()=>{const offers=Array.isArray(profile.offerLetters)?profile.offerLetters:[];return offers.length?"\n📄 *Offer Letter"+(offers.length>1?"s":"")+"*: "+offers.map((o,i)=>`${i===0?"★ ":""}${o.status||""}${o.university?` — ${o.university}`:""}${o.country?`, ${o.country}`:""}${o.intakeSeason&&o.intakeSeason!=="Not found"?` (${o.intakeSeason})`:""}`).join(" | "):"";})()}

🎓 *Academic Background*
• Highest Qualification: ${profile.program||"N/A"}${profile.yearOfPassing&&profile.yearOfPassing!=="Not found"?` (${profile.yearOfPassing})`:""}
• University: ${profile.university||"N/A"}
• Result/GPA: ${profile.academicResult||"N/A"}
${(()=>{
  const tests = Array.isArray(profile.englishTests) && profile.englishTests.length > 0 ? profile.englishTests : [];
  if (tests.length > 0) {
    return tests.map(et => {
      const subs = et.subScores ? Object.entries(et.subScores).filter(([,v])=>v&&v!=="").map(([k,v])=>`${k.charAt(0).toUpperCase()+k.slice(1)}:${v}`).join(" ") : "";
      const urn  = et.urn && et.urn !== "Not found" && et.urn !== "" ? ` | URN: ${et.urn}` : "";
      const date = et.testDate && et.testDate !== "Not found" ? ` (${et.testDate})` : "";
      return `• ${et.type||"English Test"}: ${et.overallScore||"N/A"}${date}${subs?` | ${subs}`:""}${urn}`;
    }).join("\n");
  }
  const parts = [];
  if (profile.ieltsScore && profile.ieltsScore !== "Not found") parts.push(`• IELTS: ${profile.ieltsScore}`);
  if (profile.toeflScore && profile.toeflScore !== "Not found") parts.push(`• TOEFL: ${profile.toeflScore}`);
  if (profile.pteScore   && profile.pteScore   !== "Not found") parts.push(`• PTE: ${profile.pteScore}`);
  return parts.join("\n") || "• English Tests: N/A";
})()}${profile.otherEnglishTest&&profile.otherEnglishTest!=="Not found"?`\n• Other English: ${profile.otherEnglishTest}`:""}${profile.mediumOfInstruction&&profile.mediumOfInstruction!=="Not found"?`\n• Medium of Instruction: ${profile.mediumOfInstruction}`:""}${profile.studyGap&&profile.studyGap!=="Not found"?`\n⚠️ Study Gap: ${profile.studyGap}`:""}

💰 *Financial*
• Account Holder: ${profile.financialHolder||"N/A"}
• Funds Available: ${profile.financialBalance||"N/A"}${profile.fundsRequired?`\n• Required: ${profile.fundsRequired}`:""}${(()=>{if(!profile.fundsRequired||!profile.financialBalance)return"";const a=parseCurrencyAmount(profile.financialBalance),r=parseCurrencyAmount(profile.fundsRequired);if(a.amount===null||r.amount===null)return"\n• Sufficiency: Cannot parse — verify manually";if(a.currency!==r.currency)return"\n• Sufficiency: ⚠️ Currencies differ — verify manually";const d=a.amount-r.amount;return d>=0?`\n• Sufficiency: ✓ Sufficient (+${a.currency} ${d.toLocaleString()})`:`\n• Sufficiency: ✗ Shortfall of ${a.currency} ${Math.abs(d).toLocaleString()}`;})()}

📊 *Eligibility Scores*
• Overall: ${results.eligibility.overallScore}/100 (${scoreLabel(results.eligibility.overallScore)})
• Financial: ${results.eligibility.financialScore}/100
• Academic: ${results.eligibility.academicScore}/100
• Documents: ${results.eligibility.documentScore}/100

📋 *Summary*
${results.eligibility.summary||"N/A"}

⚠️ *Gaps & Concerns:* ${results.missingDocuments?.length||0}
${results.missingDocuments?.map(d=>`• ${d.document}`).join("\n")||"Nothing flagged"}

🚩 *Risk Flags:* ${results.redFlags?.length||0}
${results.redFlags?.map(f=>`• [${f.severity.toUpperCase()}] ${f.flag}`).join("\n")||"None"}${results.rejections?.length?`\n❌ *Rejections / Deferments:* ${results.rejections.length}\n${results.rejections.map(r=>`• ${r.type==="visa"?"Visa Rejection":r.type==="deferment"?"Deferment":"Admission Rejection"}${r.country?` — ${r.country}`:""}${r.university?`, ${r.university}`:""}${r.date?` (${r.date})`:""}${r.reason?`\n  ${r.reason}`:""}`).join("\n")}`:""} 

━━━━━━━━━━━━━━━━━━
Generated by VisaLens — ${new Date().toLocaleDateString()}` : "No data available";

  const waShort = profile && results ? [
    `🎓 *VisaLens Report — ${profile.fullName||"Student"}*`,
    `🌍 ${profile.nationality||"N/A"} | 📅 DOB: ${profile.dob||"N/A"}`,
    `🛂 Passport: ${profile.passportNumber||"N/A"} (Exp: ${profile.passportExpiry||"N/A"})`,
    (()=>{ const o = Array.isArray(profile.offerLetters)&&profile.offerLetters[0]; return o ? `📄 Offer: ${o.status||""} — ${o.university||""}${o.country?`, ${o.country}`:""}` : ""; })(),
    `🎓 ${profile.program||"N/A"} | Result: ${profile.academicResult||"N/A"}`,
    (()=>{ const t = Array.isArray(profile.englishTests)&&profile.englishTests[0]; return t ? `📝 ${t.type||"English"}: ${t.overallScore||"N/A"}` : profile.ieltsScore&&profile.ieltsScore!=="Not found" ? `📝 IELTS: ${profile.ieltsScore}` : ""; })(),
    `💰 Funds: ${profile.financialBalance||"N/A"}`,
    `📊 Score: ${results.eligibility.overallScore}/100 — ${scoreLabel(results.eligibility.overallScore)}`,
    results.redFlags?.length ? `🚩 Flags: ${results.redFlags.slice(0,3).map(f=>`[${f.severity.toUpperCase()}] ${f.flag}`).join(" | ")}` : "✅ No major flags",
    `━━━━━━\nGenerated by VisaLens — ${new Date().toLocaleDateString()}`,
  ].filter(Boolean).join("\n") : "No data available";

  const emailSubject = `Student Visa Assessment — ${profile?.fullName||"Student"}`;

  const email = profile && results ? `Subject: Student Visa Assessment — ${profile.fullName||"Student"}

Dear [Counselor/Student Name],

Please find below the visa readiness assessment for:

STUDENT INFORMATION
—————————————————
Name: ${profile.fullName||"N/A"}
Date of Birth: ${profile.dob||"N/A"}
Nationality: ${profile.nationality||"N/A"}
Passport No.: ${profile.passportNumber||"N/A"}
Passport Expiry: ${profile.passportExpiry||"N/A"}

ACADEMIC BACKGROUND
—————————————————
Highest Qualification: ${profile.program||"N/A"}${profile.yearOfPassing&&profile.yearOfPassing!=="Not found"?` (${profile.yearOfPassing})`:""}
University: ${profile.university||"N/A"}
Academic Result/GPA: ${profile.academicResult||"N/A"}

FINANCIAL STATUS
—————————————————
Account Holder: ${profile.financialHolder||"N/A"}
Balance: ${profile.financialBalance||"N/A"}${profile.fundsRequired?`\nRequired: ${profile.fundsRequired}`:""}

ELIGIBILITY ASSESSMENT
—————————————————
Overall Score: ${results.eligibility.overallScore}/100 — ${scoreLabel(results.eligibility.overallScore)}
Financial Strength: ${results.eligibility.financialScore}/100
Academic Standing: ${results.eligibility.academicScore}/100
Document Completeness: ${results.eligibility.documentScore}/100

Summary: ${results.eligibility.summary||"N/A"}

GAPS & CONCERNS (${results.missingDocuments?.length||0})
—————————————————
${results.missingDocuments?.map(d=>`• ${d.document}: ${d.reason}`).join("\n")||"Nothing flagged"}

RISK FLAGS (${results.redFlags?.length||0})
—————————————————
${results.redFlags?.map(f=>`• [${f.severity.toUpperCase()}] ${f.flag}\n  ${f.detail}`).join("\n\n")||"No significant risk flags"}

—————————————————
This report was generated by VisaLens on ${new Date().toLocaleDateString()}.
Please verify all information before submission.` : "No data available";

  function copy() { navigator.clipboard.writeText(mode==="whatsapp"?wa:email); setCopied(true); setTimeout(()=>setCopied(false),2000); }

  function openWhatsApp() {
    const num = phone.replace(/\D/g, "");
    if (!num) { alert("Please enter a WhatsApp number with country code (e.g. 447911123456)"); return; }
    window.open(`https://wa.me/${num}?text=${encodeURIComponent(waShort)}`, "_blank");
  }

  function openEmail() {
    if (!emailAddr.trim()) { alert("Please enter an email address"); return; }
    window.location.href = `mailto:${emailAddr.trim()}?subject=${encodeURIComponent(emailSubject)}&body=${encodeURIComponent(email)}`;
  }

  return (
    <div className="overlay" onClick={e=>e.target===e.currentTarget&&onClose()}>
      <div className="report-modal" role="dialog">
        <div className="modal-hdr"><div className="rc-ico"><Send size={14}/></div><span className="modal-title">Share Report</span><button className="btn-ico" onClick={onClose}><X size={14}/></button></div>
        <div className="report-body">
          <div className="report-tabs">
            <button className={`report-tab${mode==="whatsapp"?" on":""}`} onClick={()=>setMode("whatsapp")}><MessageSquare size={13}/>WhatsApp</button>
            <button className={`report-tab${mode==="email"?" on":""}`}    onClick={()=>setMode("email")}><Mail size={13}/>Email</button>
          </div>
          <div className="report-text">{mode==="whatsapp"?wa:email}</div>

          <div style={{display:"flex",flexDirection:"column",gap:8,marginTop:4}}>
            <button className={`copy-btn ${mode}`} onClick={copy}>
              {copied?<><Check size={15}/>Copied!</>:<><Copy size={15}/>Copy {mode==="whatsapp"?"for WhatsApp":"for Email"}</>}
            </button>

            {mode==="whatsapp" && (
              <div style={{display:"flex",gap:8,alignItems:"center"}}>
                <input type="tel" value={phone} onChange={e=>setPhone(e.target.value)}
                  placeholder="Phone with country code e.g. 447911123456"
                  style={{flex:1,padding:"8px 12px",borderRadius:"var(--r1)",border:"1px solid var(--bd)",background:"var(--s2)",color:"var(--t1)",fontSize:13,outline:"none"}}/>
                <button className="btn-p" style={{whiteSpace:"nowrap",height:36,paddingLeft:14,paddingRight:14,fontSize:13}} onClick={openWhatsApp}>
                  <MessageSquare size={14}/>Open in WhatsApp
                </button>
              </div>
            )}

            {mode==="email" && (
              <div style={{display:"flex",gap:8,alignItems:"center"}}>
                <input type="email" value={emailAddr} onChange={e=>setEmailAddr(e.target.value)}
                  placeholder="recipient@email.com"
                  style={{flex:1,padding:"8px 12px",borderRadius:"var(--r1)",border:"1px solid var(--bd)",background:"var(--s2)",color:"var(--t1)",fontSize:13,outline:"none"}}/>
                <button className="btn-p" style={{whiteSpace:"nowrap",height:36,paddingLeft:14,paddingRight:14,fontSize:13}} onClick={openEmail}>
                  <Mail size={14}/>Open in Mail
                </button>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
